---

name: Linter Checks

on:
  push:
    branches: [ "master" ]
    paths:
      - sdk/**
  pull_request:
    branches: [ "master" ]
    paths:
      - sdk/**

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  run-format-check:

    container:
      image: ${{ vars.PTI_DOCKER_IMAGE }}

    if: vars.PTI_RUN_TESTS == 1

    runs-on: [self-hosted, Linux, pti]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Environment Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade setuptools wheel pip
          pip install clang-format==14

      - name: Check SDK Format
        working-directory: sdk
        run: |
          mkdir build
          cd build
          # Expedited configure
          cmake .. -DPTI_BUILD_TESTING=OFF -DPTI_BUILD_SAMPLES=OFF -DPTI_INSTALL=OFF
          make format-chk
